spring:
  application:
    name: order-service
  rabbitmq:
    host: 172.199.17.30
    port: 5672
    username: admin
    password: admin
#server: 
#  port: 8201
#  
  
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
feign: 
  hystrix: 
    enabled: true

management: 
  endpoints: 
    web: 
      exposure: 
        include: hystrix.steam
---
spring: 
  profiles: order1
  
server: 
  port: 8201
---
spring: 
  profiles: order2
  
server: 
  port: 8202
